<?php
/**
 * AuthCodeResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FullContact APIs
 *
 * Lookup and enrich individuals by sending any identifiers you may already have, such as an email address, Twitter handle or phone number. These identifiers will then be used to locate and return any additional information we may have, such as a person’s name and social handles.
 *
 * OpenAPI spec version: 3.0.0-oas3
 * Contact: support@fullcontact.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AuthCodeResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthCodeResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AuthCodeResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'access_token_expiration' => 'int',
'access_token_expiration_date' => '\DateTime',
'refresh_token_expiration' => 'int',
'refresh_token_expiration_date' => '\DateTime',
'access_token' => 'string',
'refresh_token' => 'string',
'scope' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'access_token_expiration' => 'int64',
'access_token_expiration_date' => 'date-time',
'refresh_token_expiration' => 'int64',
'refresh_token_expiration_date' => 'date-time',
'access_token' => null,
'refresh_token' => null,
'scope' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_token_expiration' => 'access_token_expiration',
'access_token_expiration_date' => 'access_token_expiration_date',
'refresh_token_expiration' => 'refresh_token_expiration',
'refresh_token_expiration_date' => 'refresh_token_expiration_date',
'access_token' => 'access_token',
'refresh_token' => 'refresh_token',
'scope' => 'scope'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_token_expiration' => 'setAccessTokenExpiration',
'access_token_expiration_date' => 'setAccessTokenExpirationDate',
'refresh_token_expiration' => 'setRefreshTokenExpiration',
'refresh_token_expiration_date' => 'setRefreshTokenExpirationDate',
'access_token' => 'setAccessToken',
'refresh_token' => 'setRefreshToken',
'scope' => 'setScope'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_token_expiration' => 'getAccessTokenExpiration',
'access_token_expiration_date' => 'getAccessTokenExpirationDate',
'refresh_token_expiration' => 'getRefreshTokenExpiration',
'refresh_token_expiration_date' => 'getRefreshTokenExpirationDate',
'access_token' => 'getAccessToken',
'refresh_token' => 'getRefreshToken',
'scope' => 'getScope'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['access_token_expiration'] = isset($data['access_token_expiration']) ? $data['access_token_expiration'] : null;
        $this->container['access_token_expiration_date'] = isset($data['access_token_expiration_date']) ? $data['access_token_expiration_date'] : null;
        $this->container['refresh_token_expiration'] = isset($data['refresh_token_expiration']) ? $data['refresh_token_expiration'] : null;
        $this->container['refresh_token_expiration_date'] = isset($data['refresh_token_expiration_date']) ? $data['refresh_token_expiration_date'] : null;
        $this->container['access_token'] = isset($data['access_token']) ? $data['access_token'] : null;
        $this->container['refresh_token'] = isset($data['refresh_token']) ? $data['refresh_token'] : null;
        $this->container['scope'] = isset($data['scope']) ? $data['scope'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_token_expiration
     *
     * @return int
     */
    public function getAccessTokenExpiration()
    {
        return $this->container['access_token_expiration'];
    }

    /**
     * Sets access_token_expiration
     *
     * @param int $access_token_expiration access_token_expiration
     *
     * @return $this
     */
    public function setAccessTokenExpiration($access_token_expiration)
    {
        $this->container['access_token_expiration'] = $access_token_expiration;

        return $this;
    }

    /**
     * Gets access_token_expiration_date
     *
     * @return \DateTime
     */
    public function getAccessTokenExpirationDate()
    {
        return $this->container['access_token_expiration_date'];
    }

    /**
     * Sets access_token_expiration_date
     *
     * @param \DateTime $access_token_expiration_date access_token_expiration_date
     *
     * @return $this
     */
    public function setAccessTokenExpirationDate($access_token_expiration_date)
    {
        $this->container['access_token_expiration_date'] = $access_token_expiration_date;

        return $this;
    }

    /**
     * Gets refresh_token_expiration
     *
     * @return int
     */
    public function getRefreshTokenExpiration()
    {
        return $this->container['refresh_token_expiration'];
    }

    /**
     * Sets refresh_token_expiration
     *
     * @param int $refresh_token_expiration refresh_token_expiration
     *
     * @return $this
     */
    public function setRefreshTokenExpiration($refresh_token_expiration)
    {
        $this->container['refresh_token_expiration'] = $refresh_token_expiration;

        return $this;
    }

    /**
     * Gets refresh_token_expiration_date
     *
     * @return \DateTime
     */
    public function getRefreshTokenExpirationDate()
    {
        return $this->container['refresh_token_expiration_date'];
    }

    /**
     * Sets refresh_token_expiration_date
     *
     * @param \DateTime $refresh_token_expiration_date refresh_token_expiration_date
     *
     * @return $this
     */
    public function setRefreshTokenExpirationDate($refresh_token_expiration_date)
    {
        $this->container['refresh_token_expiration_date'] = $refresh_token_expiration_date;

        return $this;
    }

    /**
     * Gets access_token
     *
     * @return string
     */
    public function getAccessToken()
    {
        return $this->container['access_token'];
    }

    /**
     * Sets access_token
     *
     * @param string $access_token access_token
     *
     * @return $this
     */
    public function setAccessToken($access_token)
    {
        $this->container['access_token'] = $access_token;

        return $this;
    }

    /**
     * Gets refresh_token
     *
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->container['refresh_token'];
    }

    /**
     * Sets refresh_token
     *
     * @param string $refresh_token refresh_token
     *
     * @return $this
     */
    public function setRefreshToken($refresh_token)
    {
        $this->container['refresh_token'] = $refresh_token;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string $scope scope
     *
     * @return $this
     */
    public function setScope($scope)
    {
        $this->container['scope'] = $scope;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
