<?php
/**
 * EmailVerificationEmailsEmailAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FullContact APIs
 *
 * Lookup and enrich individuals by sending any identifiers you may already have, such as an email address, Twitter handle or phone number. These identifiers will then be used to locate and return any additional information we may have, such as a person’s name and social handles.
 *
 * OpenAPI spec version: 3.0.0-oas3
 * Contact: support@fullcontact.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmailVerificationEmailsEmailAttributes Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailVerificationEmailsEmailAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmailVerification_emails_email_attributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'valid_syntax' => 'bool',
'deliverable' => 'bool',
'catchall' => 'bool',
'risky' => 'bool',
'disposable' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'valid_syntax' => null,
'deliverable' => null,
'catchall' => null,
'risky' => null,
'disposable' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'valid_syntax' => 'validSyntax',
'deliverable' => 'deliverable',
'catchall' => 'catchall',
'risky' => 'risky',
'disposable' => 'disposable'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'valid_syntax' => 'setValidSyntax',
'deliverable' => 'setDeliverable',
'catchall' => 'setCatchall',
'risky' => 'setRisky',
'disposable' => 'setDisposable'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'valid_syntax' => 'getValidSyntax',
'deliverable' => 'getDeliverable',
'catchall' => 'getCatchall',
'risky' => 'getRisky',
'disposable' => 'getDisposable'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['valid_syntax'] = isset($data['valid_syntax']) ? $data['valid_syntax'] : null;
        $this->container['deliverable'] = isset($data['deliverable']) ? $data['deliverable'] : null;
        $this->container['catchall'] = isset($data['catchall']) ? $data['catchall'] : null;
        $this->container['risky'] = isset($data['risky']) ? $data['risky'] : null;
        $this->container['disposable'] = isset($data['disposable']) ? $data['disposable'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets valid_syntax
     *
     * @return bool
     */
    public function getValidSyntax()
    {
        return $this->container['valid_syntax'];
    }

    /**
     * Sets valid_syntax
     *
     * @param bool $valid_syntax valid_syntax
     *
     * @return $this
     */
    public function setValidSyntax($valid_syntax)
    {
        $this->container['valid_syntax'] = $valid_syntax;

        return $this;
    }

    /**
     * Gets deliverable
     *
     * @return bool
     */
    public function getDeliverable()
    {
        return $this->container['deliverable'];
    }

    /**
     * Sets deliverable
     *
     * @param bool $deliverable deliverable
     *
     * @return $this
     */
    public function setDeliverable($deliverable)
    {
        $this->container['deliverable'] = $deliverable;

        return $this;
    }

    /**
     * Gets catchall
     *
     * @return bool
     */
    public function getCatchall()
    {
        return $this->container['catchall'];
    }

    /**
     * Sets catchall
     *
     * @param bool $catchall catchall
     *
     * @return $this
     */
    public function setCatchall($catchall)
    {
        $this->container['catchall'] = $catchall;

        return $this;
    }

    /**
     * Gets risky
     *
     * @return bool
     */
    public function getRisky()
    {
        return $this->container['risky'];
    }

    /**
     * Sets risky
     *
     * @param bool $risky risky
     *
     * @return $this
     */
    public function setRisky($risky)
    {
        $this->container['risky'] = $risky;

        return $this;
    }

    /**
     * Gets disposable
     *
     * @return bool
     */
    public function getDisposable()
    {
        return $this->container['disposable'];
    }

    /**
     * Sets disposable
     *
     * @param bool $disposable disposable
     *
     * @return $this
     */
    public function setDisposable($disposable)
    {
        $this->container['disposable'] = $disposable;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
