<?php
/**
 * TranscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FullContact APIs
 *
 * Lookup and enrich individuals by sending any identifiers you may already have, such as an email address, Twitter handle or phone number. These identifiers will then be used to locate and return any additional information we may have, such as a person’s name and social handles.
 *
 * OpenAPI spec version: 3.0.0-oas3
 * Contact: support@fullcontact.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TranscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Transcription
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranscriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Transcription"
     */
    public function testTranscription()
    {
    }

    /**
     * Test attribute "last_webhook_attempt"
     */
    public function testPropertyLastWebhookAttempt()
    {
    }

    /**
     * Test attribute "v_card_url"
     */
    public function testPropertyVCardUrl()
    {
    }

    /**
     * Test attribute "unverified_v_card_url"
     */
    public function testPropertyUnverifiedVCardUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "webhook_attempts"
     */
    public function testPropertyWebhookAttempts()
    {
    }

    /**
     * Test attribute "webhook_url"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "quality"
     */
    public function testPropertyQuality()
    {
    }

    /**
     * Test attribute "submitted"
     */
    public function testPropertySubmitted()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "unverified_fields"
     */
    public function testPropertyUnverifiedFields()
    {
    }

    /**
     * Test attribute "unverified_contact"
     */
    public function testPropertyUnverifiedContact()
    {
    }
}
