<?php
/**
 * ContactsAPIApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FullContact APIs
 *
 * Lookup and enrich individuals by sending any identifiers you may already have, such as an email address, Twitter handle or phone number. These identifiers will then be used to locate and return any additional information we may have, such as a person’s name and social handles.
 *
 * OpenAPI spec version: 3.0.0-oas3
 * Contact: support@fullcontact.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ContactsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactsAPIApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for exchangeAuthCode
     *
     * Get Access Token.
     *
     */
    public function testExchangeAuthCode()
    {
    }

    /**
     * Test case for v1AccountGetPost
     *
     * Get Account.
     *
     */
    public function testV1AccountGetPost()
    {
    }

    /**
     * Test case for v1AuthVerifyAccessTokenPost
     *
     * Validate Access Token.
     *
     */
    public function testV1AuthVerifyAccessTokenPost()
    {
    }

    /**
     * Test case for v1ContactsCreatePost
     *
     * Create a Contact.
     *
     */
    public function testV1ContactsCreatePost()
    {
    }

    /**
     * Test case for v1ContactsDeletePost
     *
     * Delete a Contact.
     *
     */
    public function testV1ContactsDeletePost()
    {
    }

    /**
     * Test case for v1ContactsGetPost
     *
     * Get Contacts by ID.
     *
     */
    public function testV1ContactsGetPost()
    {
    }

    /**
     * Test case for v1ContactsManageTagsPost
     *
     * Manage Contact Tags.
     *
     */
    public function testV1ContactsManageTagsPost()
    {
    }

    /**
     * Test case for v1ContactsScrollPost
     *
     * List Contacts.
     *
     */
    public function testV1ContactsScrollPost()
    {
    }

    /**
     * Test case for v1ContactsSearchPost
     *
     * Search Contacts.
     *
     */
    public function testV1ContactsSearchPost()
    {
    }

    /**
     * Test case for v1ContactsUpdatePost
     *
     * Update a Contact.
     *
     */
    public function testV1ContactsUpdatePost()
    {
    }

    /**
     * Test case for v1ContactsUploadPhotoPost
     *
     * Upload a Contact Photo.
     *
     */
    public function testV1ContactsUploadPhotoPost()
    {
    }

    /**
     * Test case for v1OauthRefreshTokenPost
     *
     * Refresh Access Token.
     *
     */
    public function testV1OauthRefreshTokenPost()
    {
    }

    /**
     * Test case for v1TagsCreatePost
     *
     * Create a Tag.
     *
     */
    public function testV1TagsCreatePost()
    {
    }

    /**
     * Test case for v1TagsDeletePost
     *
     * Delete a Tag.
     *
     */
    public function testV1TagsDeletePost()
    {
    }

    /**
     * Test case for v1TagsGetPost
     *
     * Get Tags by ID.
     *
     */
    public function testV1TagsGetPost()
    {
    }

    /**
     * Test case for v1TagsScrollPost
     *
     * List Tags.
     *
     */
    public function testV1TagsScrollPost()
    {
    }

    /**
     * Test case for v1TagsUpdatePost
     *
     * Rename a Tag.
     *
     */
    public function testV1TagsUpdatePost()
    {
    }

    /**
     * Test case for v1TeamsGetPost
     *
     * List Teams.
     *
     */
    public function testV1TeamsGetPost()
    {
    }

    /**
     * Test case for v1WebhooksCreatePost
     *
     * Create a Webhook.
     *
     */
    public function testV1WebhooksCreatePost()
    {
    }

    /**
     * Test case for v1WebhooksDeletePost
     *
     * Delete a Webhook.
     *
     */
    public function testV1WebhooksDeletePost()
    {
    }

    /**
     * Test case for v1WebhooksGetBatchesPost
     *
     * Get Webhook Batches.
     *
     */
    public function testV1WebhooksGetBatchesPost()
    {
    }

    /**
     * Test case for v1WebhooksGetPost
     *
     * Get Webhooks by ID.
     *
     */
    public function testV1WebhooksGetPost()
    {
    }

    /**
     * Test case for v1WebhooksGetTriggersPost
     *
     * Get Available Triggers.
     *
     */
    public function testV1WebhooksGetTriggersPost()
    {
    }

    /**
     * Test case for v1WebhooksSearchPost
     *
     * Search Webhooks.
     *
     */
    public function testV1WebhooksSearchPost()
    {
    }
}
